package-lock.json
package.json

Updated noble-mac dependency to [PR version that I submitted to noble-mac](https://github.com/Timeular/noble-mac/pull/8) that will work correctly on Linux/Windows. The recent change to noble-mac broke node-poweredup on any non-Mac OS.
I've tested this fix on Linux. The Noble library doesn't work with my Windows Bluetooth adapter, but it should work the same there. I don't have access to Mac OS to test, but there shouldn't be any issue with Mac as well.

Updated noble-mac dependency

---

DOCS.md
README.md
package-lock.json
src/duplotrainbase.ts

I don't think the Duplo train has a distance sensor.

remove colorAndDistance event from DuploTrainBase docs

---

examples/train_controller.js

Replaced "Devices.LED_LIGHTS" with "DeviceType.LED_LIGHTS" 
Because "Devices.LED_LIGHTS" is undefined (maybe deprecated)

Fixed broken device type query

---

.npmignore

It allows to import the sources to be bundled with main app if needed
E.g:
```js
import { PoweredUp } from 'node-poweredup/src/poweredup-browser';
const poweredUP = new PoweredUP();
```
Then the lib is not exposed to the `window` scope and bundled with the app source.

Remove sources from npmignore

---

src/boostmovehub.ts
src/hub.ts
src/interfaces.ts
src/lpf2hub.ts
src/wedo2smarthub.ts

As per the official protocol specification all 4 byte version numbers are using BCD number encoding: https://lego.github.io/lego-ble-wireless-protocol-docs/index.html#version-number-encoding

LPF2 firmware versions should be decoded with BCD

---

package-lock.json
src/duplotrainbase.ts
src/lpf2hub.ts
src/pupremote.ts

Duplo train LED has both indexed color and rgb modes just like other hubs, so it can be controlled with the same code.

allow RGB led control for the duplo train hub

---

src/hub.ts

The error checking allowed case insensitive port name lookup, but the actual access was done case sensitive.

allow case insensitive port names

---

src/lpf2hub.ts
src/wedo2smarthub.ts

WeDo tilt sensor in Mode 0 and Boost Move tilt sensor in mode 4 both return signed 8 bit integers. So they can be directly read as such.
The existing code was causing 2 issues:
- WeDo tilt X axis value was always positive (in both directions)
- Boost move mode 4 range is -128 to 127, so some negative values were reported as positive in range 128 - 160
Also the sign of the raw read was sometimes reversed, not sure if this was intentional. I undone it, but could be reverted to maintain backwards compatibility.

Fix and simplify tilt sensor reading

---

src/hub.ts

Trying to switch to mode 0 resulted in switching to the default mode (for example mode 4 for boost tilt sensor).

allow switching to mode 0 in Hub.subscribe()

---

src/consts.ts
src/hub.ts
src/lpf2hub.ts
src/utils.ts

This extends the information obtained with port mode info requests and disables them by default (to reduce unnecessary radio chatter).
New information includes:
- Identifying all know device types by name
- Port mode combinations
- FW/HW versions
- value format

 Extended port information requests

---

src/poweredup-browser.ts
src/poweredup-node.ts

Predictable pull request following #47 
Allow to retrieve hub by its primary MAC address but:
- it assumes those addresses are really unique (they should be)
- if not it returns the first hub found matching provided address

Add PoweredUP#getConnectedHubByPrimaryMACAddress

---

src/lpf2hub.ts

The address in the message is prefixed by its length (6) which was interpreted as part of the address.

fixed address readout

---

src/hub.ts

As asked in #53, if `attach` event should be emitted whatever the value of `autoSubscribe`, here is the PR to fix it.

Emit attach event any case

---

src/poweredup-browser.ts
src/webbleabstraction.ts

It has been a while since [this comment](https://github.com/nathankellenicki/node-poweredup/pull/64#issuecomment-566673521) but never too late...
This should improve the mailbox used in the browser while waiting for the hub type message.
It should works with multiple/partial message per frame and prevent message dropping when reading mailbox.

Improve web ble mailbox

---

src/hubs/lpf2hub.ts

I think the expression was wrong: we want to parse if the message length is less or equal to buffer size.

Fix message length comparison

---

src/hubs/lpf2hub.ts

This replaces several magic numbers in the lpf2hub implementation with constants that were already present in src/consts.ts. This should enhance readability and maintainability. Comments that were made redundant by including the constant names have been removed.
There are still quite a few magic numbers in here that could be replaced, particularly in the byte arrays used to build messages, but I didn't attempt to clean those up.

Replace magic numbers with constants

---

src/devices/absolutemotor.ts
src/devices/device.ts
src/devices/tachomotor.ts
src/hubs/lpf2hub.ts

* changed _finished pointer to array to not overwrite callbacks
* all completed and discarded commands get resolved
* 0x10 bitset exists in documentation only? -> not implemented
I have done only a few tests with my technic hubs and motors, but I would expect this to work with all devices. A better solution than this could be to register callbacks for all commands. Then it is possible to only resolve those that completed and reject the discarded ones. For my current project I do not need this, but it might be handy for others.
Below all combinations of feedback bits I managed to produce:
```
const feedback0x01 = () => { // normal operation, one command in progress sends 0x01 followed by 0x0a when finished
setInterval(() => {
motorA.rotateByDegrees(1,100);
}, 1000);
}
const feedback0x05 = …
```

possible fix for #118, always return resolve

---

src/consts.ts

Looks like the Event enum got the wrong name, so I've updated it

Rename events enum from AlertPayload to Event

---

src/devices/technicmediumhubtiltsensor.ts

This adds some probably rarely required functionality, feel free to decline. 
My problem was that the tilt angle approaching y=90 and y=-90 seems to be inaccurate, e.g. you can see it jumping form y=85 directly to y=90. To verify one can compare to the angle using the acceleration values which I ended up using:
```
hub.on("accel", (device, { x, y, z }) => {
const X = Math.round(Math.atan2(y, z)*180/Math.PI);
const Y = -Math.round(Math.atan2(x, Math.sqrt(y**2 + z**2))*180/Math.PI);
console.log(`accel (X: ${X}, Y: ${Y}`);
});
hub.on("tilt", (device, { x, y, z }) => {
console.log(`tilt  (X: ${x}, Y: ${y}, Z: ${z}`);
});
```
My original goal was to configure the orientation like mentioned here https://lego.github.io/lego-ble-wireless-protocol-docs/#output-sub-command-tiltconfigorientation-orie …

add impact count mode to tiltsensor

---

src/devices/technicmediumhubtiltsensor.ts

Before merging this it would be good if someone else can confirm that they also see the same problem. All my technicmediumhubs have this issue and I can use this workaround to correct it, but it could be that e.g. all my hubs are from some batch that has been put upside down in some factory calibration routine or maybe this is some bug in the firmware that is fixed by lego already and I simply use outdated firmware.
The problem is the following:
If the hub was an airplane, then the z angle of the tilt would be the heading angle. If the airplane flies straight into the ground or straight up, the heading is undefined, one can chose any value. However the roll angle which is x is not undefined, but it depends on the choice of heading angle which defines from what angle to start applying the …

add workaround for wrong tilt orientation

---

src/devices/colordistancesensor.ts

I know the distances in general are not very accurate and it depends on the material used for testing how the infrared based distance value and light based partial value combine. But still, with this simplification my overall results were better.

change colordistancesensor distance calculation

---

src/devices/device.ts
src/hubs/lpf2hub.ts

I found time to find answers to the remaining open questions from 
#118
* feedback for multiple port ids in one message can be obtained when using two motors combined to a virtual port. Stopping an ongoing command for the virtual port by a command to one of its components returns feedback for the virtual port and the individual port in one message.
* the startup and completion bits can be changed to make the command buffer instead of executing immediately or to not request completion feedback
* the 0x10 busy/full feedback can be obtained when dropping the execute immediately bit. Currently you have to use device.send(....) directly for this.
I tested the change with my technic hubs and motors only, but I would expect it to work for all hubs and even if it does not it should not cause any …

Command feedback

---

src/poweredup-browser.ts

fix for issue #152 as suggested there
I don't have a mario hub to test

Add missing Mario hub to poweredup-browser

---

package.json
src/poweredup-browser.ts
src/webbleabstraction.ts

Fix race in _determineLPF2HubType that makes a connection fall in Android web Bluetooth (see #157 )

Fix for #157 (and possibly #131)
